const data = [
  {
    name: "First",
    id: "id-1",
    submissions: 3443,
    tag: "Graph Theory",
    difficulty_level: "Easy",
  },
  {
    name: "Second",
    id: "id-2",
    submissions: 245,
    tag: "Number Theory",
    difficulty_level: "Easy",
  },
  {
    name: "Third",
    id: "id-3",
    submissions: 456,
    tag: "Dynamic Programming",
    difficulty_level: "Medium",
  },
  {
    name: "Fourth",
    id: "id-4",
    submissions: 243,
    tag: "Recursion",
    difficulty_level: "Hard",
  },
  {
    name: "Fifth",
    id: "id-5",
    submissions: 768,
    tag: "Number Theory",
    difficulty_level: "Easy",
  },
  {
    name: "Sixth",
    id: "id-6",
    submissions: 463,
    tag: "Graph Theory",
    difficulty_level: "Medium",
  },
  {
    name: "Seventh",
    id: "id-7",
    submissions: 235,
    tag: "Number Theory",
    difficulty_level: "Easy",
  },
  {
    name: "Eighth",
    id: "id-8",
    submissions: 868,
    tag: "Graph Theory",
    difficulty_level: "Hard",
  },
  {
    name: "Ninth",
    id: "id-9",
    submissions: 258,
    tag: "Number Theory",
    difficulty_level: "Hard",
  },
  {
    name: "Tenth",
    id: "id-10",
    submissions: 876,
    tag: "Dynamic Programming",
    difficulty_level: "Easy",
  },
  {
    name: "Eleventh",
    id: "id-11",
    submissions: 235,
    tag: "Graph Theory",
    difficulty_level: "Medium",
  },
  {
    name: "Tweleth",
    id: "id-12",
    submissions: 954,
    tag: "Recursion",
    difficulty_level: "Easy",
  },
  {
    name: "Thirteenth",
    id: "id-13",
    submissions: 258,
    tag: "Number Theory",
    difficulty_level: "Easy",
  },
  {
    name: "Fourteenth",
    id: "id-14",
    submissions: 853,
    tag: "Dynamic Programming",
    difficulty_level: "Medium",
  },
  {
    name: "Fifteenth",
    id: "id-15",
    submissions: 267,
    tag: "Brute Force",
    difficulty_level: "Medium",
  },
  {
    name: "Sixteenth",
    id: "id-16",
    submissions: 156,
    tag: "Graph Theory",
    difficulty_level: "Hard",
  },
  {
    name: "Seventeenth",
    id: "id-17",
    submissions: 825,
    tag: "Brute Force",
    difficulty_level: "Medium",
  },
];

export default data;
